name: Rust Workflow

on:
  push:

jobs:
  rust:
    name: Check Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run format check
        run: cargo fmt --all -- --check
      - name: Run linter
        run: cargo clippy
